# Generated by Django 5.1.1 on 2024-09-24 15:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeperformance',
            name='employee_rating',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeeperformance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
