# Generated by Django 5.1.1 on 2024-10-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='display_name',
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(help_text="Role name (e.g., 'Admin', 'Manager', 'Employee')", max_length=100, unique=True),
        ),
    ]
