# Generated by Django 5.1.1 on 2024-09-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('executive_director', 'Executive Director'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
