# Generated by Django 5.1.1 on 2024-11-04 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_role_display_name_alter_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='desk_access',
            field=models.BooleanField(default=True, help_text='Allow desk access'),
        ),
        migrations.AddField(
            model_name='role',
            name='desk_shortcuts',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='role',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='is_custom',
            field=models.BooleanField(default=True, help_text='Is this a custom role'),
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(help_text='Role name', max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctype', models.CharField(help_text='Document Type', max_length=255)),
                ('permission_type', models.CharField(choices=[('create', 'Create'), ('read', 'Read'), ('write', 'Write'), ('delete', 'Delete'), ('submit', 'Submit'), ('cancel', 'Cancel'), ('amend', 'Amend'), ('report', 'Report')], max_length=20)),
                ('value', models.IntegerField(default=0, help_text='Permission Level (0 or 1)')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='accounts.role')),
            ],
            options={
                'unique_together': {('role', 'doctype', 'permission_type')},
            },
        ),
    ]
