# Generated by Django 5.1.1 on 2024-09-15 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
