# Generated by Django 5.1.1 on 2024-09-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('executive_director', 'Executive Director'), ('employee', 'Employee'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
