# Generated by Django 5.1.1 on 2024-11-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_role_desk_access_role_desk_shortcuts_role_disabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='erpnext_customer_id',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
