# Generated by Django 5.1.1 on 2024-11-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_erpnext_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='erpnext_sync_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='erpnext_sync_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='erpnext_user_id',
            field=models.CharField(blank=True, help_text='User ID in ERPNext system', max_length=140, null=True),
        ),
    ]
