# Generated by Django 5.1.1 on 2024-11-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_erpnext_sync_error_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Profile photo.', null=True, upload_to='profile_photos/'),
        ),
    ]
