# Generated by Django 5.1.1 on 2024-09-13 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
        ('employee', '0003_alter_employee_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='executive_director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executive_director_of', to='employee.employee'),
        ),
    ]
